return {
    ["TowAttached"] = "",
    ["TowDetached"] = "",
    ["TowSnapped"] = "",
    ["TowCut"] = "",
    ["BedVehicleLoaded"] = "",
    ["BedVehicleUnloaded"] = "",
    ["BedVehicleMoved"] = "",
    ["BedCableAttached"] = "",
    ["BedCableDetached"] = "",
    ["WinchInstalled"] = "",
    ["WinchRemoved"] = "",
    ["WinchCableLoaded"] = "",
    ["WinchCableRemoved"] = "",
    ["WinchDurabilityLow"] = "",
    ["WinchWornOut"] = "",
    ["AdminAction"] = "",
}